services:
  backend-service-blue:
    build:
      context: ./backend-service
    environment:
      - API_PORT=3000
    
  backend-service-green:
    build:
      context: ./backend-service
    environment:
      - API_PORT=3000

  reverse-proxy:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./backend-service/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend-service-blue
      - backend-service-green