name: backend-service Continuous deployment

on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - 'backend-service/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Rebuild and deploy backend container
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
      run: |
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' > id_rsa
        chmod 600 id_rsa
        ssh -o StrictHostKeyChecking=no -i id_rsa $SSH_USER@$SSH_HOST << 'EOF'
          cd MapGuesser/
          git pull origin main
          cd backend-service/
          docker stop api
          docker build -t mapguesser_api:latest . 
          docker run -d --rm -p 3000:3000 --name api mapguesser_api:latest
        EOF